import { DishType } from '@/types/DishType';
import { PromocodeType, ReviewType } from '@/types';

export interface RestaurantType {
  id: string;
  name: string;
  image: string;
  rating: string;
  time: string;
  price: string;
  discount: string;
  cuisine: string;
}

export const popularRestaurants: RestaurantType[] = [
  {
    id: 'res_1',
    name: 'Ishtaa Pure Veg',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=300&auto=format&fit=crop',
    rating: '4.7',
    time: '25-35 min',
    price: '₹250 for one',
    discount: '20% off on first order',
    cuisine: 'Pure Vegetarian Restaurants, Satvik Meals',
  },
  {
    id: 'res_2',
    name: 'Jain Bhoj',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=300&auto=format&fit=crop',
    rating: '4.8',
    time: '30-40 min',
    price: '₹200 for one',
    discount: 'Free delivery above ₹299',
    cuisine: 'Jain Food, Pure Vegetarian Restaurants',
  },
  {
    id: 'res_3',
    name: 'Sattvik Kitchen',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=300&auto=format&fit=crop',
    rating: '4.6',
    time: '35-45 min',
    price: '₹180 for one',
    discount: 'Traditional Satvik Meals',
    cuisine: 'Satvik Meals, Jain Food',
  },
  {
    id: 'res_4',
    name: 'Green Garden Bowls',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=300&auto=format&fit=crop',
    rating: '4.5',
    time: '20-30 min',
    price: '₹220 for one',
    discount: '15% off on orders above ₹400',
    cuisine: 'Healthy Foods, Organic Food Partners',
  },
  {
    id: 'res_5',
    name: 'Organic Roots',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=300&auto=format&fit=crop',
    rating: '4.9',
    time: '40-55 min',
    price: '₹300 for one',
    discount: 'Organic Guarantee',
    cuisine: 'Organic Food Partners, Healthy Foods',
  },
  {
    id: 'res_6',
    name: 'Prasadam Bhavan',
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?q=80&w=300&auto=format&fit=crop',
    rating: '4.9',
    time: '30-45 min',
    price: '₹120 for one',
    discount: 'Blessed food, pure & divine',
    cuisine: 'Temple Prasadam Deliveries, Pure Vegetarian Restaurants',
  },
  {
    id: 'res_7',
    name: 'Vrinda Veg Express',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=300&auto=format&fit=crop',
    rating: '4.3',
    time: '20-30 min',
    price: '₹150 for one',
    discount: '10% off for repeat customers',
    cuisine: 'Pure Vegetarian Restaurants',
  },
  {
    id: 'res_8',
    name: 'Ayur Kitchen',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?q=80&w=300&auto=format&fit=crop',
    rating: '4.7',
    time: '35-50 min',
    price: '₹240 for one',
    discount: 'Eat well, live well',
    cuisine: 'Healthy Foods, Satvik Meals, Organic Food Partners',
  }
];

export const mockDishes: (DishType & { restaurantId?: string })[] = [
  {
    id: 'food_1_1',
    name: 'Masala Dosa',
    price: 89,
    image: 'https://images.unsplash.com/photo-1668236543005-c9e54a558509?w=400',
    description: 'Crispy rice crepe filled with spiced potato',
    category: 'South Indian',
    type: 'food',
    cookingTime: 15,
    weight: '250g',
    rating: 4.7,
    isPopular: true,
    isRecommended: true,
    ingredients: ['Rice batter', 'Potato', 'Ghee', 'Sambar spices'],
    isAvailable: true,
    restaurantId: 'res_1'
  },
  {
    id: 'food_1_2',
    name: 'Idli Sambar',
    price: 69,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400',
    description: 'Steamed rice cakes with lentil soup and chutneys',
    category: 'South Indian',
    type: 'food',
    cookingTime: 10,
    weight: '200g',
    rating: 4.5,
    isPopular: false,
    isRecommended: true,
    ingredients: ['Rice', 'Urad Dal', 'Lentils', 'Chutneys'],
    isAvailable: true,
    restaurantId: 'res_1'
  },
  {
    id: 'food_1_3',
    name: 'Rava Upma',
    price: 79,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=400',
    description: 'Semolina cooked with vegetables and spices',
    category: 'South Indian',
    type: 'food',
    cookingTime: 12,
    weight: '220g',
    rating: 4.3,
    isPopular: false,
    isRecommended: false,
    ingredients: ['Semolina', 'Vegetables', 'Ghee', 'Cashew nuts'],
    isAvailable: true,
    restaurantId: 'res_1'
  },
  {
    id: 'food_2_1',
    name: 'Jain Dal Baati',
    price: 189,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    description: 'No root veggies — pure Jain dal with crispy bati',
    category: 'Jain Specials',
    type: 'food',
    cookingTime: 25,
    weight: '350g',
    rating: 4.8,
    isPopular: true,
    isRecommended: true,
    ingredients: ['Wheat flour', 'Yellow lentils', 'Ghee', 'Jain spices'],
    isAvailable: true,
    restaurantId: 'res_2'
  },
  {
    id: 'food_2_2',
    name: 'Paneer Tikka (Jain)',
    price: 229,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400',
    description: 'Marinated paneer without onion-garlic',
    category: 'Starters',
    type: 'food',
    cookingTime: 20,
    weight: '300g',
    rating: 4.7,
    isPopular: true,
    isRecommended: false,
    ingredients: ['Paneer', 'Yogurt', 'Tomato', 'Capsicum', 'Spices'],
    isAvailable: true,
    restaurantId: 'res_2'
  },
  {
    id: 'food_3_1',
    name: 'Satvik Thali',
    price: 199,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400',
    description: 'No onion, no garlic — dal, sabzi, roti, rice, dessert',
    category: 'Thali',
    type: 'food',
    cookingTime: 30,
    weight: '500g',
    rating: 4.8,
    isPopular: true,
    isRecommended: true,
    ingredients: ['Rice', 'Whole wheat flour', 'Lentils', 'Seasonal vegetables'],
    isAvailable: true,
    restaurantId: 'res_3'
  },
  {
    id: 'food_3_2',
    name: 'Lauki Kofta Curry',
    price: 149,
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400',
    description: 'Bottle gourd dumplings in satvik tomato gravy',
    category: 'Main Course',
    type: 'food',
    cookingTime: 22,
    weight: '400g',
    rating: 4.5,
    isPopular: false,
    isRecommended: false,
    ingredients: ['Bottle gourd', 'Tomato', 'Gram flour', 'Spices'],
    isAvailable: true,
    restaurantId: 'res_3'
  },
  {
    id: 'food_4_1',
    name: 'Quinoa Power Bowl',
    price: 299,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=300&auto=format&fit=crop',
    description: 'Quinoa, roasted veggies, avocado, tahini dressing',
    category: 'Bowls',
    type: 'food',
    cookingTime: 15,
    weight: '350g',
    rating: 4.6,
    isPopular: true,
    isRecommended: true,
    ingredients: ['Quinoa', 'Avocado', 'Roasted vegetables', 'Tahini'],
    isAvailable: true,
    restaurantId: 'res_4'
  },
  {
    id: 'food_4_2',
    name: 'Garden Fresh Salad',
    price: 199,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=300&auto=format&fit=crop',
    description: 'Mixed greens, cherry tomatoes, cucumber, lemon vinaigrette',
    category: 'Salads',
    type: 'food',
    cookingTime: 10,
    weight: '280g',
    rating: 4.4,
    isPopular: false,
    isRecommended: false,
    ingredients: ['Mixed greens', 'Cherry tomatoes', 'Cucumber', 'Lemon dressing'],
    isAvailable: true,
    restaurantId: 'res_4'
  },
  {
    id: 'food_5_1',
    name: 'Organic Veg Thali',
    price: 349,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    description: 'Seasonal organic vegetables, millet roti, A2 ghee',
    category: 'Thali',
    type: 'food',
    cookingTime: 35,
    weight: '550g',
    rating: 4.9,
    isPopular: true,
    isRecommended: true,
    ingredients: ['Organic vegetables', 'Millets', 'A2 ghee', 'Brown rice'],
    isAvailable: true,
    restaurantId: 'res_5'
  },
  {
    id: 'food_5_2',
    name: 'Millet Khichdi',
    price: 199,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
    description: 'Foxtail millet cooked with organic vegetables',
    category: 'Main Course',
    type: 'food',
    cookingTime: 20,
    weight: '400g',
    rating: 4.7,
    isPopular: false,
    isRecommended: true,
    ingredients: ['Foxtail millet', 'Organic vegetables', 'Moong Dal', 'Spices'],
    isAvailable: true,
    restaurantId: 'res_5'
  },
  {
    id: 'food_6_1',
    name: 'ISKCON Khichdi Prasad',
    price: 89,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=400',
    description: 'Divine khichdi offered at the temple, served with ghee',
    category: 'Prasadam',
    type: 'food',
    cookingTime: 15,
    weight: '350g',
    rating: 4.9,
    isPopular: true,
    isRecommended: true,
    ingredients: ['Rice', 'Moong Dal', 'Pure Ghee', 'Vegetables', 'Camphor hint'],
    isAvailable: true,
    restaurantId: 'res_6'
  },
  {
    id: 'food_6_2',
    name: 'Puri Sabzi Prasad',
    price: 99,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400',
    description: 'Sacred puri with potato sabzi',
    category: 'Prasadam',
    type: 'food',
    cookingTime: 15,
    weight: '300g',
    rating: 4.8,
    isPopular: true,
    isRecommended: false,
    ingredients: ['Whole wheat flour', 'Potatoes', 'Temple spices', 'Pure oil'],
    isAvailable: true,
    restaurantId: 'res_6'
  },
  {
    id: 'food_7_1',
    name: 'Paneer Butter Masala',
    price: 199,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
    description: 'Rich, creamy tomato-based paneer curry',
    category: 'Main Course',
    type: 'food',
    cookingTime: 25,
    weight: '400g',
    rating: 4.5,
    isPopular: true,
    isRecommended: true,
    ingredients: ['Paneer', 'Tomato gravy', 'Butter', 'Cream', 'Spices'],
    isAvailable: true,
    restaurantId: 'res_7'
  },
  {
    id: 'food_7_2',
    name: 'Dal Makhani',
    price: 169,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
    description: 'Slow-cooked black lentils in buttery gravy',
    category: 'Main Course',
    type: 'food',
    cookingTime: 30,
    weight: '450g',
    rating: 4.6,
    isPopular: false,
    isRecommended: false,
    ingredients: ['Black lentils', 'Kidney beans', 'Butter', 'Cream', 'Spices'],
    isAvailable: true,
    restaurantId: 'res_7'
  },
  {
    id: 'food_8_1',
    name: 'Tridosha Balancing Thali',
    price: 299,
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400',
    description: 'Ayurvedic meal designed to balance Vata, Pitta, Kapha',
    category: 'Thali',
    type: 'food',
    cookingTime: 35,
    weight: '500g',
    rating: 4.8,
    isPopular: true,
    isRecommended: true,
    ingredients: ['Ayurvedic herbs', 'Brown rice', 'Lentil soup', 'Steamed vegetables'],
    isAvailable: true,
    restaurantId: 'res_8'
  }
];

export const mockPromocodes: PromocodeType[] = [
  {
    id: 1,
    name: 'Veg Dash Welcome Offer',
    code: 'VEGDASH50',
    discount: 50,
    expiresAt: '2026-12-31',
    isActive: true,
    logo: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=150',
  },
  {
    id: 2,
    name: 'Veg Dash Mega Saving',
    code: 'VEGDASH100',
    discount: 30,
    expiresAt: '2026-12-31',
    isActive: true,
    logo: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=150',
  },
  {
    id: 3,
    name: 'Jain Specials Discount',
    code: 'JAIN25',
    discount: 25,
    expiresAt: '2026-12-31',
    isActive: true,
    logo: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=150',
  }
];

export const mockReviews: ReviewType[] = [
  {
    id: 1,
    name: 'Aarav Mehta',
    rating: 5,
    date: '2026-06-10',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150',
    comment: 'The food from Ishtaa was incredibly pure and delicious. The Jain Dal Makhani was cooked perfectly without onion or garlic!',
  },
  {
    id: 2,
    name: 'Ananya Sharma',
    rating: 4.5,
    date: '2026-06-12',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150',
    comment: 'Fast delivery and excellent packaging. Sambar was hot and idlis were super soft.',
  },
  {
    id: 3,
    name: 'Rahul Verma',
    rating: 5,
    date: '2026-06-14',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150',
    comment: 'Finally a 100% vegetarian food app. The Satvik meals are amazing for daily orders.',
  }
];
