import { DishType } from '@/types/DishType';
import { PromocodeType, ReviewType } from '@/types';

export interface RestaurantType {
  id: string;
  name: string;
  image: string;
  rating: string;
  time: string;
  price: string;
  discount: string;
  cuisine: string;
}

export const popularRestaurants: RestaurantType[] = [
  {
    id: 'chutneys',
    name: 'Chutneys',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?q=80&w=300&auto=format&fit=crop',
    rating: '4.6',
    time: '30-35 mins',
    price: '₹200 for one',
    discount: '50% OFF up to ₹100',
    cuisine: 'South Indian, Vegetarian',
  },
  {
    id: 'ishtaa',
    name: 'Ishtaa',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=300&auto=format&fit=crop',
    rating: '4.5',
    time: '25-30 mins',
    price: '₹250 for one',
    discount: '50% OFF up to ₹100',
    cuisine: 'North Indian, Jain Specials',
  },
  {
    id: 'saravana_bhavan',
    name: 'Saravana Bhavan',
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?q=80&w=300&auto=format&fit=crop',
    rating: '4.4',
    time: '20-25 mins',
    price: '₹150 for one',
    discount: '40% OFF up to ₹80',
    cuisine: 'Pure South Indian, Tiffins',
  },
  {
    id: 'haldirams',
    name: "Haldiram's Sweets & Restaurant",
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=300&auto=format&fit=crop',
    rating: '4.3',
    time: '15-20 mins',
    price: '₹180 for one',
    discount: '30% OFF up to ₹75',
    cuisine: 'North Indian, Chaat, Desserts',
  }
];

export const mockDishes: (DishType & { restaurantId?: string })[] = [
  // Healthy Foods Category (IDs 1-10)
  {
    id: 1,
    name: 'Mushroom Soup',
    price: 160,
    image: 'https://george-fx.github.io/mesio-data/dishes/01-mushroom-soup.jpg',
    description: 'Rich and velvety mushroom soup made with fresh forest mushrooms, aromatic herbs and finished with cream.',
    category: 'Healthy Foods',
    type: 'food',
    cookingTime: 30,
    weight: '350g',
    rating: 4.5,
    isPopular: true,
    isRecommended: false,
    ingredients: ['mushrooms', 'onion', 'garlic', 'vegetable broth', 'cream', 'butter', 'salt', 'pepper'],
    isAvailable: true,
    restaurantId: 'ishtaa'
  },
  {
    id: 2,
    name: 'Noodle Soup',
    price: 180,
    image: 'https://george-fx.github.io/mesio-data/dishes/02-noodle-soup.jpg',
    description: 'Comforting veggie noodle soup with tender veggies, fresh noodles, and garden herbs in homemade vegetable broth.',
    category: 'Healthy Foods',
    type: 'food',
    cookingTime: 25,
    weight: '400g',
    rating: 4.2,
    isPopular: true,
    isRecommended: false,
    ingredients: ['noodles', 'vegetable broth', 'carrots', 'celery', 'onion', 'tofu', 'salt', 'pepper'],
    isAvailable: true,
    restaurantId: 'ishtaa'
  },
  {
    id: 3,
    name: 'Japanese Ramen',
    price: 260,
    image: 'https://george-fx.github.io/mesio-data/dishes/03-japanese-ramen.jpg',
    description: 'Authentic vegetarian Japanese ramen with rich miso broth, tender noodles, grilled tofu, soft-boiled egg, and fresh green onions.',
    category: 'Healthy Foods',
    type: 'food',
    cookingTime: 40,
    weight: '450g',
    rating: 4.8,
    isPopular: true,
    isRecommended: false,
    ingredients: ['ramen noodles', 'tofu', 'soy sauce', 'egg', 'nori', 'green onion', 'bamboo shoots', 'vegetable broth'],
    isAvailable: true,
    restaurantId: 'ishtaa'
  },
  {
    id: 4,
    name: 'Miso Soup',
    price: 150,
    image: 'https://george-fx.github.io/mesio-data/dishes/04-miso-soup.jpg',
    description: 'Traditional Japanese miso soup with premium white miso paste, dashi broth, tofu, and wakame seaweed.',
    category: 'Healthy Foods',
    type: 'food',
    cookingTime: 15,
    weight: '300g',
    rating: 4.3,
    isPopular: true,
    isRecommended: false,
    ingredients: ['miso paste', 'dashi broth', 'tofu', 'wakame seaweed', 'green onion'],
    isAvailable: true,
    restaurantId: 'ishtaa'
  },
  {
    id: 5,
    name: 'Quinoa Avocado Salad',
    price: 190,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=300&auto=format&fit=crop',
    description: 'Organic quinoa tossed with fresh avocado slices, cherry tomatoes, cucumbers, and a lemon-herb dressing.',
    category: 'Healthy Foods',
    type: 'food',
    cookingTime: 10,
    weight: '280g',
    rating: 4.6,
    isPopular: true,
    isRecommended: true,
    ingredients: ['quinoa', 'avocado', 'tomatoes', 'cucumber', 'lemon juice', 'olive oil'],
    isAvailable: true,
    restaurantId: 'ishtaa'
  },
  {
    id: 6,
    name: 'Steamed Tofu & Broccoli',
    price: 170,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=300&auto=format&fit=crop',
    description: 'Organic broccoli florets and tofu cubes lightly steamed, seasoned with low-sodium soy sauce and ginger.',
    category: 'Healthy Foods',
    type: 'food',
    cookingTime: 12,
    weight: '320g',
    rating: 4.4,
    isPopular: false,
    isRecommended: false,
    ingredients: ['tofu', 'broccoli', 'soy sauce', 'ginger', 'sesame seeds'],
    isAvailable: true,
    restaurantId: 'ishtaa'
  },

  // Pure Vegetarian Restaurants Category (IDs 100-199)
  {
    id: 101,
    name: 'Special Masala Dosa',
    price: 130,
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?q=80&w=300&auto=format&fit=crop',
    description: 'Crisp rice and lentil crepe filled with spiced potato mash, served with three signature chutneys and sambar.',
    category: 'Pure Vegetarian Restaurants',
    type: 'food',
    cookingTime: 12,
    weight: '250g',
    rating: 4.7,
    isPopular: true,
    isRecommended: true,
    ingredients: ['rice batter', 'potato mash', 'ghee', 'mustard seeds', 'curry leaves'],
    isAvailable: true,
    restaurantId: 'chutneys'
  },
  {
    id: 102,
    name: 'Steamed Idli Sambar (2 Pcs)',
    price: 80,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=300&auto=format&fit=crop',
    description: 'Soft, fluffy steamed rice cakes served with hot lentils soup (sambar) and coconut chutney.',
    category: 'Pure Vegetarian Restaurants',
    type: 'food',
    cookingTime: 8,
    weight: '200g',
    rating: 4.5,
    isPopular: false,
    isRecommended: true,
    ingredients: ['fermented rice', 'lentils', 'sambar spices'],
    isAvailable: true,
    restaurantId: 'chutneys'
  },
  {
    id: 103,
    name: 'South Indian Filter Coffee',
    price: 60,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=300&auto=format&fit=crop',
    description: 'Traditional chicory-infused hot milk coffee brewed in a brass metal filter, served foaming in a dabarah.',
    category: 'Pure Vegetarian Restaurants',
    type: 'drink',
    cookingTime: 5,
    weight: '150ml',
    rating: 4.9,
    isPopular: true,
    isRecommended: true,
    ingredients: ['milk', 'coffee powder', 'chicory', 'sugar'],
    isAvailable: true,
    restaurantId: 'chutneys'
  },
  {
    id: 104,
    name: 'Paneer Butter Masala',
    price: 240,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?q=80&w=300&auto=format&fit=crop',
    description: 'Fresh cottage cheese cubes cooked in a rich, creamy, and mildly sweet tomato and cashew gravy.',
    category: 'Pure Vegetarian Restaurants',
    type: 'food',
    cookingTime: 20,
    weight: '400g',
    rating: 4.6,
    isPopular: true,
    isRecommended: false,
    ingredients: ['paneer', 'tomato gravy', 'cashews', 'cream', 'butter'],
    isAvailable: true,
    restaurantId: 'chutneys'
  },
  {
    id: 105,
    name: 'Butter Naan',
    price: 60,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?q=80&w=300&auto=format&fit=crop',
    description: 'Soft and fluffy leavened flatbread baked in a tandoor, brushed generously with butter.',
    category: 'Pure Vegetarian Restaurants',
    type: 'food',
    cookingTime: 10,
    weight: '120g',
    rating: 4.4,
    isPopular: false,
    isRecommended: false,
    ingredients: ['refined flour', 'yogurt', 'yeast', 'butter'],
    isAvailable: true,
    restaurantId: 'chutneys'
  },
  {
    id: 106,
    name: 'Veg Hakka Noodles',
    price: 180,
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?q=80&w=300&auto=format&fit=crop',
    description: 'Stir-fried noodles cooked with crunchy cabbage, bell peppers, carrots, and spring onions in a light soy sauce.',
    category: 'Pure Vegetarian Restaurants',
    type: 'food',
    cookingTime: 15,
    weight: '350g',
    rating: 4.5,
    isPopular: true,
    isRecommended: false,
    ingredients: ['noodles', 'cabbage', 'capsicum', 'carrots', 'soy sauce', 'spring onion'],
    isAvailable: true,
    restaurantId: 'chutneys'
  },
  {
    id: 107,
    name: 'Gobi Manchurian Dry',
    price: 160,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?q=80&w=300&auto=format&fit=crop',
    description: 'Crispy deep-fried cauliflower florets tossed in a sweet, tangy, and slightly spicy Manchurian sauce.',
    category: 'Pure Vegetarian Restaurants',
    type: 'food',
    cookingTime: 18,
    weight: '300g',
    rating: 4.3,
    isPopular: false,
    isRecommended: true,
    ingredients: ['cauliflower', 'cornflour', 'ginger-garlic', 'soya sauce', 'chilli sauce'],
    isAvailable: true,
    restaurantId: 'chutneys'
  },

  // Jain Food Category (IDs 200-299)
  {
    id: 201,
    name: 'Dal Makhani (Jain Special)',
    price: 250,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=300&auto=format&fit=crop',
    description: 'Black lentils slow-cooked overnight with cream, butter, and Jain-friendly spices (no onion, no garlic).',
    category: 'Jain Food',
    type: 'food',
    cookingTime: 25,
    weight: '400g',
    rating: 4.8,
    isPopular: true,
    isRecommended: true,
    ingredients: ['black lentils', 'butter', 'cream', 'jain spices'],
    isAvailable: true,
    restaurantId: 'ishtaa'
  },
  {
    id: 202,
    name: 'Veg Dum Biryani',
    price: 280,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=300&auto=format&fit=crop',
    description: 'Aromatic basmati rice layered with fresh vegetables, spices, and saffron, slow-cooked in dum style.',
    category: 'Pure Vegetarian Restaurants',
    type: 'food',
    cookingTime: 30,
    weight: '450g',
    rating: 4.7,
    isPopular: true,
    isRecommended: true,
    ingredients: ['basmati rice', 'mixed vegetables', 'saffron', 'mint', 'rose water'],
    isAvailable: true,
    restaurantId: 'ishtaa'
  },
  {
    id: 203,
    name: 'Hariyali Paneer Tikka',
    price: 220,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=300&auto=format&fit=crop',
    description: 'Cottage cheese marinated in a green paste of mint, coriander, and yogurt, grilled to perfection in tandoor.',
    category: 'Healthy Foods',
    type: 'food',
    cookingTime: 18,
    weight: '250g',
    rating: 4.6,
    isPopular: false,
    isRecommended: false,
    ingredients: ['paneer', 'mint', 'coriander', 'yogurt', 'lemon juice'],
    isAvailable: true,
    restaurantId: 'ishtaa'
  },
  {
    id: 204,
    name: 'Jain Paneer Tikka Masala',
    price: 260,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=300&auto=format&fit=crop',
    description: 'Grilled cottage cheese cubes cooked in a rich Jain-friendly tomato-gravy without onion or garlic.',
    category: 'Jain Food',
    type: 'food',
    cookingTime: 22,
    weight: '400g',
    rating: 4.7,
    isPopular: true,
    isRecommended: true,
    ingredients: ['paneer', 'tomato', 'cashew paste', 'jain spices', 'cream'],
    isAvailable: true,
    restaurantId: 'ishtaa'
  },
  {
    id: 205,
    name: 'Jain Dal Fry',
    price: 180,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=300&auto=format&fit=crop',
    description: 'Yellow lentils tempered with cow ghee, cumin seeds, tomatoes, and green chillies (no onion/garlic).',
    category: 'Jain Food',
    type: 'food',
    cookingTime: 12,
    weight: '350g',
    rating: 4.4,
    isPopular: false,
    isRecommended: false,
    ingredients: ['yellow lentils', 'tomatoes', 'ghee', 'cumin', 'green chilli'],
    isAvailable: true,
    restaurantId: 'ishtaa'
  },
  {
    id: 302,
    name: 'Mini Ghee Idli (10 Pcs)',
    price: 120,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=300&auto=format&fit=crop',
    description: 'Bite-sized baby idlis soaked in piping hot sambar, topped generously with pure ghee.',
    category: 'Jain Food',
    type: 'food',
    cookingTime: 10,
    weight: '220g',
    rating: 4.8,
    isPopular: true,
    isRecommended: false,
    ingredients: ['idli batter', 'sambar', 'ghee'],
    isAvailable: true,
    restaurantId: 'saravana_bhavan'
  },

  // Organic Food Partners Category (IDs 400-499)
  {
    id: 401,
    name: 'Raj Kachori Chaat',
    price: 110,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?q=80&w=300&auto=format&fit=crop',
    description: 'Organic large kachori stuffed with boiled potatoes, sprouts, sweetened yogurt, chutneys, and topped with sev.',
    category: 'Organic Food Partners',
    type: 'food',
    cookingTime: 5,
    weight: '300g',
    rating: 4.7,
    isPopular: true,
    isRecommended: true,
    ingredients: ['kachori shell', 'sprouts', 'sweet yogurt', 'tamarind chutney', 'mint chutney'],
    isAvailable: true,
    restaurantId: 'haldirams'
  },
  {
    id: 402,
    name: 'Kesar Rasmalai (2 Pcs)',
    price: 90,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=300&auto=format&fit=crop',
    description: 'Soft cottage cheese dumplings soaked in sweet, saffron-flavored milk, garnished with organic pistachios.',
    category: 'Organic Food Partners',
    type: 'drink',
    cookingTime: 5,
    weight: '180g',
    rating: 4.9,
    isPopular: true,
    isRecommended: true,
    ingredients: ['milk', 'saffron', 'paneer dumplings', 'pistachios'],
    isAvailable: true,
    restaurantId: 'haldirams'
  },
  {
    id: 403,
    name: 'Organic Fruit Chaat',
    price: 120,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=300&auto=format&fit=crop',
    description: 'A refreshing mix of fresh organic seasonal fruits tossed with tangy chaat masala and lemon juice.',
    category: 'Organic Food Partners',
    type: 'food',
    cookingTime: 6,
    weight: '250g',
    rating: 4.5,
    isPopular: true,
    isRecommended: false,
    ingredients: ['apple', 'banana', 'papaya', 'pineapple', 'chaat masala', 'lemon juice'],
    isAvailable: true,
    restaurantId: 'haldirams'
  },
  {
    id: 404,
    name: 'Organic Oats Dosa',
    price: 140,
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?q=80&w=300&auto=format&fit=crop',
    description: 'Crispy and healthy crepe made from organic rolled oats batter, served with coconut chutney.',
    category: 'Organic Food Partners',
    type: 'food',
    cookingTime: 12,
    weight: '220g',
    rating: 4.4,
    isPopular: false,
    isRecommended: true,
    ingredients: ['rolled oats', 'yogurt', 'green chilli', 'ginger', 'coconut chutney'],
    isAvailable: true,
    restaurantId: 'saravana_bhavan'
  },

  // Satvik Meals Category (IDs 500-599)
  {
    id: 501,
    name: 'Satvik Dal Khichdi',
    price: 160,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=300&auto=format&fit=crop',
    description: 'Comforting, easily digestible rice and lentil porridge cooked with ghee and turmeric without onion or garlic.',
    category: 'Satvik Meals',
    type: 'food',
    cookingTime: 18,
    weight: '400g',
    rating: 4.8,
    isPopular: true,
    isRecommended: true,
    ingredients: ['rice', 'moong dal', 'cow ghee', 'turmeric', 'ginger', 'cumin seeds'],
    isAvailable: true,
    restaurantId: 'ishtaa'
  },
  {
    id: 502,
    name: 'Satvik Veg Pulao',
    price: 180,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=300&auto=format&fit=crop',
    description: 'Simple steamed basmati rice with organic farm-fresh veggies, cooked in cow ghee and mild spices.',
    category: 'Satvik Meals',
    type: 'food',
    cookingTime: 20,
    weight: '350g',
    rating: 4.6,
    isPopular: false,
    isRecommended: false,
    ingredients: ['basmati rice', 'carrots', 'peas', 'beans', 'ghee', 'cardamom'],
    isAvailable: true,
    restaurantId: 'saravana_bhavan'
  },
  {
    id: 503,
    name: 'Satvik Ghiya Kootu',
    price: 150,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=300&auto=format&fit=crop',
    description: 'Fresh bottle gourd (ghiya) cooked with yellow lentils and grated coconut, tempered with cumin and mustard.',
    category: 'Satvik Meals',
    type: 'food',
    cookingTime: 15,
    weight: '380g',
    rating: 4.5,
    isPopular: false,
    isRecommended: true,
    ingredients: ['bottle gourd', 'moong dal', 'coconut', 'cumin', 'mustard seeds'],
    isAvailable: true,
    restaurantId: 'saravana_bhavan'
  },
  {
    id: 504,
    name: 'Satvik Sabudana Khichdi',
    price: 140,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?q=80&w=300&auto=format&fit=crop',
    description: 'Soaked tapioca pearls sautéed with roasted peanuts, cumin, curry leaves, and green chillies in cow ghee.',
    category: 'Satvik Meals',
    type: 'food',
    cookingTime: 10,
    weight: '300g',
    rating: 4.8,
    isPopular: true,
    isRecommended: true,
    ingredients: ['tapioca pearls', 'peanuts', 'ghee', 'cumin', 'curry leaves', 'green chilli'],
    isAvailable: true,
    restaurantId: 'chutneys'
  },

  // Temple Prasadam Deliveries Category (IDs 600-699)
  {
    id: 601,
    name: 'Temple Sweet Pongal',
    price: 100,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=300&auto=format&fit=crop',
    description: 'Traditional sweet rice prasadam cooked with organic jaggery, milk, cow ghee, cashews, and cardamom.',
    category: 'Temple Prasadam Deliveries',
    type: 'food',
    cookingTime: 15,
    weight: '250g',
    rating: 4.9,
    isPopular: true,
    isRecommended: true,
    ingredients: ['raw rice', 'jaggery', 'ghee', 'cashew nuts', 'cardamom'],
    isAvailable: true,
    restaurantId: 'chutneys'
  },
  {
    id: 602,
    name: 'Temple Tamarind Rice',
    price: 110,
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?q=80&w=300&auto=format&fit=crop',
    description: 'Traditional tangy tamarind rice prasadam seasoned with peanuts, mustard seeds, curry leaves, and green chillies.',
    category: 'Temple Prasadam Deliveries',
    type: 'food',
    cookingTime: 12,
    weight: '300g',
    rating: 4.8,
    isPopular: true,
    isRecommended: true,
    ingredients: ['rice', 'tamarind paste', 'peanuts', 'mustard seeds', 'curry leaves', 'sesame oil'],
    isAvailable: true,
    restaurantId: 'saravana_bhavan'
  },
  {
    id: 603,
    name: 'Temple Curd Rice',
    price: 90,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=300&auto=format&fit=crop',
    description: 'Creamy soft rice mixed with fresh yogurt and tempered with mustard seeds, red chillies, and ginger.',
    category: 'Temple Prasadam Deliveries',
    type: 'food',
    cookingTime: 8,
    weight: '320g',
    rating: 4.7,
    isPopular: true,
    isRecommended: false,
    ingredients: ['rice', 'yogurt', 'milk', 'mustard seeds', 'ginger', 'curry leaves'],
    isAvailable: true,
    restaurantId: 'saravana_bhavan'
  },
  {
    id: 604,
    name: 'Temple Laddu (2 Pcs)',
    price: 80,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=300&auto=format&fit=crop',
    description: 'Rich sweet besan laddoos prepared with pure ghee, sugar, cashews, raisins, and a pinch of edible camphor.',
    category: 'Temple Prasadam Deliveries',
    type: 'food',
    cookingTime: 5,
    weight: '160g',
    rating: 4.9,
    isPopular: true,
    isRecommended: true,
    ingredients: ['gram flour', 'sugar', 'cow ghee', 'cashews', 'raisins', 'camphor'],
    isAvailable: true,
    restaurantId: 'chutneys'
  }
];

export const mockPromocodes: PromocodeType[] = [
  {
    id: 1,
    name: 'Veg Dash Welcome Offer',
    code: 'VEGDASH50',
    discount: 50,
    expiresAt: '2026-12-31',
    isActive: true,
    logo: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=150',
  },
  {
    id: 2,
    name: 'Veg Dash Mega Saving',
    code: 'VEGDASH100',
    discount: 30,
    expiresAt: '2026-12-31',
    isActive: true,
    logo: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=150',
  },
  {
    id: 3,
    name: 'Jain Specials Discount',
    code: 'JAIN25',
    discount: 25,
    expiresAt: '2026-12-31',
    isActive: true,
    logo: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=150',
  }
];

export const mockReviews: ReviewType[] = [
  {
    id: 1,
    name: 'Aarav Mehta',
    rating: 5,
    date: '2026-06-10',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150',
    comment: 'The food from Ishtaa was incredibly pure and delicious. The Jain Dal Makhani was cooked perfectly without onion or garlic!',
  },
  {
    id: 2,
    name: 'Ananya Sharma',
    rating: 4.5,
    date: '2026-06-12',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150',
    comment: 'Fast delivery and excellent packaging. Sambar was hot and idlis were super soft.',
  },
  {
    id: 3,
    name: 'Rahul Verma',
    rating: 5,
    date: '2026-06-14',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150',
    comment: 'Finally a 100% vegetarian food app. The Satvik meals are amazing for daily orders.',
  }
];
