export const routes = {
  FAQ: 'FAQ',
  HOME: 'Home',
  SHOP: 'Shop',
  DISH: 'Dish',
  RESTAURANT_MENU: 'RestaurantMenu',
  ONBOARDING: 'Onboarding',
  ORDER: 'Order',
  SIGN_IN: 'SignIn',
  SIGN_UP: 'SignUp',
  PROFILE: 'Profile',
  WISHLIST: 'Wishlist',
  CHECKOUT: 'Checkout',
  EDIT_PROFILE: 'EditProfile',
  NEW_PASSWORD: 'NewPassword',
  ORDER_HISTORY: 'OrderHistory',
  MY_PROMOCODES: 'MyPromocodes',
  NOTIFICATIONS: 'Notifications',
  WISHLIST_EMPTY: 'WishlistEmpty',
  ACCOUNT_CREATED: 'AccountCreated',
  CHANGE_PASSWORD: 'ChangePassword',
  FORGOT_PASSWORD: 'ForgetPassword',
  ORDER_SUCCESSFUL: 'OrderSuccessful',
  CONFIRMATION_CODE: 'ConfirmationCode',
  VERIFY_YOUR_PHONE_NUMBER: 'VerifyYourPhoneNumber',
  FORGOT_PASSWORD_SENT_EMAIL: 'ForgotPasswordSentEmail',
} as const;
